djangonautic/accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns = [
        url('signup/', views.signup_view, name="signup"),
        url('login/',views.login_view, name="login"),
        url('logout',views.logout_view,name="logout"),
        ]

djangonautic/articles/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    url('create/', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail, name="detail"),
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('index/',views.index_page),
    path('about/',views.about),
    path('services/',views.services),
    path('',article_views.article_list, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User,on_delete=models.DO_NOTHING,default=None)
    
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'
    
#py -3 manage.py makemigrations
#py -3 manage.py migrate

djangonautic/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']

djangonautic/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            #log the user in
            return redirect('articles:list')
    else:
        form=UserCreationForm
    return render(request, 'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
            #login the user  
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

djangonautic/articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles})

def article_detail(request,slug):
#    return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html',{'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method =='POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            #save article to db
            instance=form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html',{'form':form})

djangonautic/djangonautic/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.template import Context, loader
from django.shortcuts import render

def homepage(request):
#    return HttpResponse("Homepage")
    return render(request,"homepage.html")

def index_page(request):
#    return HttpResponse("Homepage")
    return render(request,"index.html")

def about(request):
#    return HttpResponse("about")
    return render(request,"about.html")

def services(request):
#    return HttpResponse("about")
    return render(request,"services.html")

djangonautic/accounts/templates/accounts/login.html
{% extends 'base_layer.html' %}
{% block content %}
 <h1>Login</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {%endif%}
    <input type="submit" value="login">
  </form>
{% endblock %}

djangonautic/accounts/templates/accounts/signup.html
{% extends 'base_layer.html' %}
{% block content %}
 <h1>SignUp</h1>
  <form class="site-form" action="index.html" method="Post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="signup">
  </form>
{% endblock %}

djangonautic/articles/templates/articles/article_create.html
{% extends 'base_layer.html' %}
{% block content %}
  <div class="create_article">
    <h2> Create an Awesome new Article</h2>
     <form class="site-form" action="{% url 'articles:create' %}"method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value = "Create">
    </form>
  </div>
  <script src="/static/slugify.js"></script>
{% endblock %}

djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layer.html' %}
{% block content %}
<div class="article-detail">
   <div class="article">
     <img src ="{{ article.thumb.url }}"/>
      <h2>{{ article.title }}</h2>
      <p>{{ article.body }}</p>
      <p>{{ article.date }}</p>
<!--   {% for article in articles %}
     <div class="article">
      <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
       <p>{{ article.snippet }}</p>
       <p>{{ article.date }}</p>
     </div>
   {% endfor %} -->
   </div>
</div>
{% endblock %}

djangonautic/articles/templates/articles/article_list.html
{% extends 'base_layer.html' %}
{% block content %}
  <h1>Articles List</h1><br>
  <div class="articles">
   {% for article in articles %}
     <div class="article">
      <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
       <p>{{ article.snippet }}</p>
       <p>{{ article.date }}</p>
       <p class="author">Added by: {{ article.author.username }}</p>
     </div>
   {% endfor %}
  </div>
{% endblock %}

djangonautic/templates/about.html
<!doctype html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="Akash Vats">
  <meta name="Keywords" content="enthusiasm, energetic blogspot">
  <meta name="Description" content="Blogs for daily enthusiasm">
  <meta name="viewport" content ="width-devoce-width">
  <title>yourBlog.com| About</title>
  <link rel="stylesheet" href="/static/style.css">
 </head>
 <body>
	<header>
		<div class="container">
			<div id="branding">
				<h1><span class="highlight">YourBlog.com</span> Web</h1>
			</div>
			<nav>
			  <ul>
			   <li><a href="index.html">Home</a></li>
			   <li class="current"><a href="about.html">About</a></li>
			   <li><a href="services.html">Services</a></li>
			  </ul>
			</nav>

		</div>
	</header>
		
	<section id="newsletter">
	  <div class="container">
	   <h1>Subscribe to our newsletter</h1>
	   <form>
	     <input type="email" placeholder="Enter Email...">
		 <button type="submit" class="button_1">Subscribe</button>
	  </div>
	</section>
	
	<section id="main">
	  <div class="container">
	    <article id="main-col">
			<h1 class="page-title">About Us</h1>
			<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. 
			</p>
			<p>
			Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
			</p>
		</article>	   
		<aside id="sidebar">
		<div class="dark">
		 <h3>What We Do</h3>
		 <p>The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz.
		 </p>
		</div>
		</aside>
	  </div>
	</section>
	<footer>
		<p>YourBlog.com, Copyright &copy; 2018</p>
	</footer>
 </body>
</html>

djangonautic/templates/base_layer.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'artstyle.css' %}">
  </head>
  <body>
    <header class="wrapper">
      <h1><a href='{% url 'home' %}'><img src="{% static 'y_logo.png' %}"/></a></h1>
      <nav>
        <ul>
        {% if user.is_authenticated %}
          <li>
            <form class = "logout-link" action = "{% url 'accounts:logout' %}" method = "post">
            {% csrf_token %}
            <button type = "submit">Logout</button>
            </form>
          </li>
          <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
<!--            <p class="user">Welcome: {{ article.author }}</p>-->
        {% else %}
           <li><a href={% url 'accounts:login' %} class="highlight">Login</a></li>
           <li><a href={% url 'accounts:signup' %} class="highlight">Signup</a></li>
        {% endif %}
        </ul>
      </nav>
    </header>
    <div class="wrapper">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

djangonautic/templates/index.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="Akash Vats">
  <meta name="Keywords" content="enthusiasm, energetic blogspot">
  <meta name="Description" content="Blogs for daily enthusiasm">
  <meta name="viewport" content ="width-devoce-width">
  <title>yourBlog.com|Welcomes you</title>
  <link rel="stylesheet" href="{% static "style.css"%}">
 </head>
 <body>
	<header>
		<div class="container">
			<div id="branding">
				<h1><span class="highlight">YourBlog.com</span> Web</h1>
			</div>
			<nav>
			  <ul>
			   <li class="current"><a href="index.html">Home</a></li>
			   <li><a href="about.html">About</a></li>
			   <li><a href="services.html">Services</a></li>
			  </ul>
			</nav>

		</div>
	</header>
	<section id="showcase">
	  <div class="container">
	   <h1>YourBlog incredible website for Blogs</h1>
	   <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
		  Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. </p>
	  </div>
	</section>
	
	<section id="newsletter">
	  <div class="container">
	   <h1>Subscribe to our newsletter</h1>
	   <form>
	     <input type="email" placeholder="Enter Email...">
		 <button type="submit" class="button_1">Subscribe</button>
	  </div>
	</section>
	
	<section id="boxes">
	  <div class="container">
	   <div class="box">
		 <img src="/static/daily_logo.png">
	     <h3>Daily Blog</h3>
		 <p>One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.</p>
	   </div>
	   <div class="box">
	     <img src="/static/YouthWeek_logo.png">
		 <h3>Weekly Blog</h3>
		 <p>One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.</p>
	   </div>
	   <div class="box">
	     <img src="/static/friends_logo.jpg">
		 <h3>Friends Blog</h3>
		 <p>One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.</p>
	   </div>	   
	</section>
	<footer>
		<p>YourBlog.com, Copyright &copy; 2018</p>
	</footer>
 </body>
</html>

djangonautic/templates/services.html
<!doctype html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Generator" content="EditPlus®">
  <meta name="Author" content="Akash Vats">
  <meta name="Keywords" content="enthusiasm, energetic blogspot">
  <meta name="Description" content="Blogs for daily enthusiasm">
  <meta name="viewport" content ="width-devoce-width">
  <title>yourBlog.com| Services</title>
  <link rel="stylesheet" href="/static/style.css">
 </head>
 <body>
	<header>
		<div class="container">
			<div id="branding">
				<h1><span class="highlight">YourBlog.com</span> Web</h1>
			</div>
			<nav>
			  <ul>
			   <li><a href="index.html">Home</a></li>
			   <li><a href="about.html">About</a></li>
			   <li class="current"><a href="services.html">Services</a></li>
			  </ul>
			</nav>

		</div>
	</header>
		
	<section id="newsletter">
	  <div class="container">
	   <h1>Subscribe to our newsletter</h1>
	   <form>
	     <input type="email" placeholder="Enter Email...">
		 <button type="submit" class="button_1">Subscribe</button>
	  </div>
	</section>
	
	<section id="main">
	  <div class="container">
	    <article id="main-col">
			<h1 class="page-title">Services</h1>
			<ul id="services">
				<li>
				<h3>Website design</h3>
				<p>The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary.</p>
				<p>Pricing: ₹600 - ₹2400</p>
				</li>
				<li>
				<h3>Website maintenance</h3>
				<p>The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary.</p>
				<p>Pricing: ₹800 - ₹3200</p>
				</li>
				<li>
				<h3>Website hosting</h3>
				<p>The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary.</p>
				<p>Pricing: ₹600 - ₹2000</p>
				</li>
			</ul>
		</article>	   
		<aside id="sidebar">
		<div class="dark">
		 <h3>Get a Quote</h3>
		 <form class="quote">
		  <div id="Q">
			<div>
			<label>Name</label><br>
			<input type="text" placeholder="Name">
			</div>
			<div>
			<label>Email</label><br>			
			<input type="email" placeholder="Email Address">
			</div>
			<div>
			<label>Email</label><br>			
			<input type="email" placeholder="Email Address">
			</div>
			<div>
			<label>Message</label><br>			
			<textarea placeholder="Message"></textarea>
			</div>
			<button class="button_1" type="submit">Send</button>
		  </div>
		 </form>
		</div>
		</aside>
	  </div>
	</section>
	<footer>
		<p>YourBlog.com, Copyright &copy; 2018</p>
	</footer>
 </body>
</html>